###############################################################################
# Outputs - Bastion
###############################################################################
output "bastion_ip" {
  description = "The public IP address assigned to the instance."
  value       = aws_instance.bastion.public_ip
}

output "bastion_sg_id" {
  description = "The ID of the Bastion Security Group."
  value       = aws_security_group.bastion_security_group.id
}

###############################################################################
# Outputs - EKS
###############################################################################
output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "eks_sg_id" {
  description = "Security group ID attached to the EKS workers."
  value       = module.eks.worker_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region."
  value       = var.region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name."
  value       = local.cluster_name
}
